### ISSUE TITLE
Views reset on every dotnet build. Also changes to cshtml do not reflect in browser

### ISSUE THREAD

**Issue by danielhursan** [umbraco/The-Starter-Kit#126]
Hey,

Can someone please describe the intended behavior of the Atomic Starter Kit with Umbraco 12?
My goal is to use it as a base, then customize it to my need, but every time I try to do a change to cshtml, my changes does not show in browser. Secondly, even if I did a change, as soon as I do a `dotnet build`, my changes are wiped and reset to the default starter kit state (like a git revert).

Is this a caching issue? What am I misssing?

Thanks,
Daniel

**Comment by nul800sebastiaan** [comment]
This is a different starter kit, I think you need to talk to these people https://atomictoolkit.com/contributors/ :-)

**Comment by danielhursan** [comment]
You're correct, my bad, thank you!
