### ISSUE TITLE
Version for v13?

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/The-Starter-Kit#127]
I'm looking at starting to update my packages for V13, I usually use The Starter Kit as a basis to build from, but there doesn't seem to be a V13 pre-release version... Is this being updated?

**Comment by AaronSadlerUK** [comment]
There is a dependency lock for < 13.0.0

![image](https://github.com/umbraco/The-Starter-Kit/assets/9937803/50149496-29b2-41e0-8657-19c4ba15d3ff)

**Comment by bergmania** [comment]
We plan to make a new version in our next sprint, starting in two weeks

**Comment by AaronSadlerUK** [comment]
@bergmania I have pushed a version which works with V13, any chance you could release this as a -beta or -rc?

It would help with getting my packages ready for the V13 stable

**Comment by bergmania** [comment]
It's available on nuget now: https://www.nuget.org/packages/Umbraco.TheStarterKit/13.0.0-rc
