### ISSUE TITLE
Adding Bootstrap and restructuring css (discussion/request)

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/The-Starter-Kit#38]
I find myself altering this starterkit a lot every time I use it because its build very specific for the starter kit. In my opinion a starterkit should be more generic while still showing the best practices in umbraco.

I suggest we add the full minified version of Bootstrap 4 witch also uses flexbox as a base for the grid.
Also i want to suggest seperating the themes from the main css and put them in a [theme_name].css.
in the past I did this with a stylesheet picker to add the themes (screenshots below). This way we can make it easier to add new themes.

I'm curious what you think of these changes.

![theme picker](https://user-images.githubusercontent.com/29602162/38610570-8e437c72-3d81-11e8-8117-ad0e27574500.png)
![theme picker 2](https://user-images.githubusercontent.com/29602162/38610572-9146ff3e-3d81-11e8-815f-a0562af6f448.png)

**Comment by nul800sebastiaan** [comment]
Hey @FransdeJong - Sorry for the (very) late reply 🙈

I think it's cool, but we're working on a new starterkit in the next few months. So I think making large changes to this one would not be the best way to spend your time. Thanks for the offer though! 👍
