### ISSUE TITLE
Installing package when site is virtual application does not work correctly

### ISSUE THREAD

**Issue by skidmow** [umbraco/The-Starter-Kit#47]
I completed an empty Umbraco installation, then set it up in IIS as a Virtual Application (sub application beneath another website).

I then logged into this application via the IIS bindings and installed The Starter Kit from the back-office. The installation is successful, but the files are installed in the wrong folders. The views are all installed correctly in the Views folder, however everything else is installed in a new sub directory that shares the name of the Virtual Application (Umbraco-7-9-2). Please see attached screenshot. As a result the views can't find the partials. If I resolve that, the CSS cannot be found etc. until all the files are manually moved.

I don't know if this is an Umbraco wide problem or specific to this package.

Is running Umbraco as a virtual application even supported? I have inherited a site that is setup as a virtual application and I was investigating the limitations of this when I found the error described above.

Many thanks,
Nathan

![the-starter-kit package - virtual dir install](https://user-images.githubusercontent.com/8808100/43773728-9bde2c64-9a3e-11e8-99e3-4b23dc3580a4.png)

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply 🙈

We don't plan to support virtual directories for this package, sorry. :)
