### ISSUE TITLE
Username Password

### ISSUE THREAD

**Issue by zubairhasan353** [umbraco/The-Starter-Kit#50]
When I run the project and open localhost:00000/Umbraco, it asks me for username and password. Kindly tell me the username and password. I'm new to Umbraco and watch a demo project for learning purpose.

**Comment by zubairhasan353** [comment]
When I run The-starter-Kit project and open localhost:00000/Umbraco, it asks me for username and password. Kindly tell me the username and password. I'm new to Umbraco and watch a demo project for learning purpose.

**Comment by dbeezt** [comment]
"Default Back Office user is: Email: mail@me.com Password: 1234567890" as found [here](https://github.com/umbraco/The-Starter-Kit/blob/master/README.md).
