### ISSUE TITLE
Spelling mistakes in create-content.json

### ISSUE THREAD

**Issue by vivekrajr** [umbraco/The-Starter-Kit#56]
Noticed that there are spelling mistakes in [create-content.json](https://github.com/umbraco/The-Starter-Kit/blob/2abe18f74cbce36f9d2af8533fbe1cc76b9b9cd6/src/Umbraco.SampleSite.Website/App_Plugins/StarterKit/backoffice/tours/create-content.json#L59).

Which is spelled wich

**Comment by nul800sebastiaan** [comment]
👍 I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/The-Starter-Kit/pull/57
