### ISSUE TITLE
Fix missing semi colons in starterkit

### ISSUE THREAD

**Issue by bjarnef** [umbraco/The-Starter-Kit#62]
When opening `umbraco-starterkit-app.js` in scripts editor, it has several warnings.

![image](https://user-images.githubusercontent.com/2919859/52914373-b77fd680-32c7-11e9-9430-b1507cd68832.png)

It is best practice to add semi colons at the end of these lines.

Original created here: https://github.com/umbraco/Umbraco-CMS/issues/4622

**Comment by nul800sebastiaan** [comment]
👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
