### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/The-Starter-Kit#78]
Hello,

Umbraco version: 8.14.0
New starter kit install (as of today)

I've found two issues:
 - The contact form is missing from the contact page
 - If you delete the form and remove from the contact page the front end errors with:
 
![image](https://user-images.githubusercontent.com/10153922/123437009-202d9b00-d5c7-11eb-802c-31d7a67b80e1.png)

I would love to help fix the second issue if you could point me at the source, I'm not clear from the readme if this is the correct source or not.

**Comment by nul800sebastiaan** [comment]
I am not sure what you did to get this error @RachBreeze but it looks like you're passing something into the forms macro that doesn't parse as a guid. If you have more steps to reproduce we'll be happy to look further!

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan  
To reproduce:
1) Start with an empty database
2) Install a new instance of Umbraco 8.14.0 and the latest forms.
3) Install the Umbraco starter kit
4) Navigate to the contact us page in the backoffice the form guid isn't recognised so this showed an error in the contact us page.
5) Remove the form from the contact us page, as it is not mandatory this is fine. Navigate to the front end of the website and to the contact us page.
